---
# GCP Admin service account secret - used by GCP Provider
apiVersion: v1
kind: Secret
metadata:
  name: gcp-provider-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
---
# GCP Provider with service account secret reference - used to provision sql resources
apiVersion: gcp.crossplane.io/v1alpha2
kind: Provider
metadata:
  name: gcp-sql-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    name: gcp-provider-creds
    key: credentials.json
  projectID: PROJECT_ID
  requiredPermissions:
  - cloudsql.admin
---
# ResourceClass that defines the blueprint for how a "standard" CloudSQL instance
# should be dynamically provisioned
apiVersion: database.gcp.crossplane.io/v1alpha2
kind: CloudsqlInstanceClass
metadata:
  name: standard
  namespace: crossplane-system
specTemplate:
  databaseVersion: MYSQL_5_7
  tier: db-n1-standard-1
  region: us-west2
  storageType: PD_SSD
  storageGB: 10
  providerRef:
    name: gcp-sql-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
