# Example GCP Bucket resource claim using the gcp-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: app-bucket
  namespace: app-project1-dev
spec:
  classRef:
    name: bucket-standard
  writeConnectionSecretToRef:
    name: gcsbucket
  name: example-bucket-%s
