
apiVersion: v1
kind: Namespace
metadata:
  name: complex
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: wordpress-demo-cluster
  namespace: complex
  labels:
    app: wordpress-demo
spec:
  classReference:
    name: standard-cluster
    namespace: crossplane-system
---
