---
apiVersion: v1
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
kind: Secret
metadata:
  namespace: crossplane-system
  name: gcp-provider-creds
type: Opaque
---
apiVersion: gcp.crossplane.io/v1alpha1
kind: Provider
metadata:
  namespace: crossplane-system
  name: gcp-provider
spec:
  credentialsSecretRef:
    name: gcp-provider-creds
    key: credentials.json
  projectID: PROJECT_ID
---
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-cluster
  namespace: crossplane-system
parameters:
  machineType: n1-standard-1
  numNodes: "1"
  zone: us-central1-b
provisioner: gkecluster.compute.gcp.crossplane.io/v1alpha1
providerRef:
  name: gcp-provider
reclaimPolicy: Delete
---
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-mysql
  namespace: crossplane-system
parameters:
  tier: db-n1-standard-1
  region: us-west2
  storageType: PD_SSD
provisioner: cloudsqlinstance.database.gcp.crossplane.io/v1alpha1
providerRef:
  name: gcp-provider
reclaimPolicy: Delete
