apiVersion: v1
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
---
apiVersion: aws.crossplane.io/v1alpha2
kind: Provider
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: aws-creds
  region: us-east-1
---
apiVersion: database.aws.crossplane.io/v1alpha2
kind: RDSInstanceClass
metadata:
  name: standard
  namespace: crossplane-system
specTemplate:
  class: db.t2.small
  masterUsername: masteruser
  securityGroups:
  - # sg-ab1cdefg
  - # sg-05adsfkaj1ksdjak
  size: 20
  engine: mysql
  providerRef:
    name: aws-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
