---
# ResourceClass that defines the blueprint for how a "standard" RDS instance
# should be dynamically provisioned
apiVersion: database.aws.crossplane.io/v1alpha2
kind: RDSInstanceClass
metadata:
  name: standard-aws-postgres
  namespace: crossplane-system
  annotations:
    resource: postgresqlinstance.database.crossplane.io/v1alpha1
specTemplate:
  class: db.t2.small
  masterUsername: masteruser
  securityGroups:
   - RDS_SECURITY_GROUP
  subnetGroupName: RDS_SUBNET_GROUP_NAME
  size: 20
  engine: postgresql
  providerRef:
    name: demo-aws
    namespace: crossplane-system
  reclaimPolicy: Delete
