---
## Crossplane Redis Resource class
apiVersion: cache.aws.crossplane.io/v1alpha2
kind: ReplicationGroupClass
metadata:
  name: standard-aws-redis
  namespace: crossplane-system
  annotations:
    resource: rediscluster.cache.crossplane.io/v1alpha1
specTemplate:
  engineVersion: "3.2.4"
  cacheParameterGroupName: default.redis3.2.cluster.on
  cacheNodeType: cache.t2.micro
  automaticFailoverEnabled: true
  numNodeGroups: 1
  replicasPerNodeGroup: 1
  securityGroupIds:
   - REDIS_SECURITY_GROUP
  cacheSubnetGroupName: REDIS_SUBNET_GROUP
  providerRef:
    name: demo-aws
    namespace: crossplane-system
  reclaimPolicy: Delete
