apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: app-bucket
  namespace: app-project1-dev
spec:
  name: crossplane-example-%s
  predefinedACL: Private
  localPermission: ReadWrite
  classRef:
    name: bucket-standard
  writeConnectionSecretToRef:
    name: s3bucket
