---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: app-kubernetes
  namespace: app-project1-dev
spec:
  classRef:
    name: kubernetes-standard
  writeConnectionSecretToRef:
    name: k8scluster
