apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstanceClass
metadata:
  name: mysql-standard
  namespace: app-project1-dev
  labels:
    default: "true"
classRef:
  kind: CloudsqlInstanceClass
  apiVersion: database.gcp.crossplane.io/v1alpha2
  name: cloudsqlinstancemysql-standard
  namespace: gcp-infra-dev
---
# ResourceClass that defines the blueprint for how a "standard" CloudSQL instance
# should be dynamically provisioned
apiVersion: database.gcp.crossplane.io/v1alpha2
kind: CloudsqlInstanceClass
metadata:
  name: cloudsqlinstancemysql-standard
  namespace: gcp-infra-dev
specTemplate:
  databaseVersion: MYSQL_5_6
  tier: db-custom-1-3840
  region: us-west2
  storageType: PD_SSD
  storageGB: 10
  ipv4Enabled: true
  providerRef:
    name: example
    namespace: gcp-infra-dev
  reclaimPolicy: Delete
