# Example GCP Bucket resource claim using the gcp-bucket resource class
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: gitlab-externaldiffs
  namespace: default
spec:
  classRef:
    kind: BucketClass
    apiVersion: storage.gcp.crossplane.io/v1alpha2
    name: standard-gcp-bucket
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: gitlab-externaldiffs
  name: gitlab-demo-externaldiffs-%s
