### default class
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesClusterClass
metadata:
  name: k8s-standard
  namespace: complex
classRef:
  kind: EKSClusterClass
  apiVersion: compute.aws.crossplane.io/v1alpha2
  name: standard-cluster
  namespace: crossplane-system

### cluster claim
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: wordpress-demo-cluster
  namespace: complex
  labels:
    app: wordpress-demo
spec:
  classRef:
    name: k8s-standard
  writeConnectionSecretToRef:
    name: wordpress-demo-cluster
