### default class
---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstanceClass
metadata:
  name: mysql-standard
  namespace: complex
classRef:
  kind: RDSInstanceClass
  apiVersion: database.aws.crossplane.io/v1alpha2
  name: standard-mysql
  namespace: crossplane-system

### database claim
---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: sql
  namespace: complex
spec:
  classRef:
    name: mysql-standard
  engineVersion: "5.7"
  # A secret is exported by providing the secret name
  # to export it under. This is the name of the secret
  # in the crossplane cluster, and it's scoped to this claim's namespace.
  writeConnectionSecretToRef:
    name: sql
