# ResourceClass that defines the blueprint for how a "standard" GCP bucket
# should be dynamically provisioned
apiVersion: storage.gcp.crossplane.io/v1alpha2
kind: BucketClass
metadata:
  name: standard-gcp-bucket
  namespace: crossplane-system
  annotations:
    resource: bucket.storage.crossplane.io/v1alpha1
specTemplate:
  bucketPolicyOnly:
    enabled: true
  labels:
    app: "gitlab-demo"
  location: US
  serviceAccountSecretRef:
    name: demo-gcs-creds
  storageClass: MULTI_REGIONAL
  providerRef:
    name: demo-gcp
    namespace: crossplane-system
  reclaimPolicy: Delete
