---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesClusterClass
metadata:
  name: kubernetes-standard
  namespace: app-project1-dev
  labels:
    default: "true"
classRef:
  kind: GKEClusterClass
  apiVersion: compute.gcp.crossplane.io/v1alpha2
  name: gkecluster-standard
  namespace: gcp-infra-dev
---
apiVersion: compute.gcp.crossplane.io/v1alpha2
kind: GKEClusterClass
metadata:
  name: gkecluster-standard
  namespace: gcp-infra-dev
specTemplate:
  machineType: n1-standard-1
  numNodes: 1
  zone: us-central1-b
  providerRef:
    name: example
    namespace: gcp-infra-dev
  reclaimPolicy: Delete
