## GCP Service Account Credentials
apiVersion: v1
kind: Secret
metadata:
  name: demo-gcp-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
---
## GCS Service Account Credentials
apiVersion: v1
kind: Secret
metadata:
  name: demo-gcs-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCS_PROVIDER_CREDS
  interopAccessKey: BASE64ENCODED_GCS_INTEROP_ACCESS_KEY
  interopSecret: BASE64ENCODED_GCS_INTEROP_SECRET
---
## Crossplane GCP Provider
apiVersion: gcp.crossplane.io/v1alpha2
kind: Provider
metadata:
  name: demo-gcp
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    name: demo-gcp-creds
    key: credentials.json
  projectID: PROJECT_ID
