---
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: storageaccount
  namespace: app-project1-dev
spec:
  classRef:
    name: storageaccount-standard
  writeConnectionSecretToRef:
    name: storageaccount
  name: crossplanestorageacct
