---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: app-mysql
  namespace: app-project1-dev
spec:
  writeConnectionSecretToRef:
    name: mysqlconn
  engineVersion: "5.6"
