apiVersion: storage.aws.crossplane.io/v1alpha2
kind: DBSubnetGroup
metadata:
  name: ((CONFIG_NAME))-dbsubnetgroup
  namespace: ((NAMESPACE))
spec:
  groupName: ((CONFIG_NAME))_dbsubnetgroup
  description: EKS vpc to rds
  subnetIds:
    - ((SUBNET1_ID))
    - ((SUBNET2_ID))
    - ((SUBNET3_ID))
  tags:
    - key: name
      value: ((CONFIG_NAME))-dbsubnetgroup
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
