---
apiVersion: identity.aws.crossplane.io/v1alpha2
kind: IAMRolePolicyAttachment
metadata:
  name: ((CONFIG_NAME))-role-servicepolicy
  namespace: ((NAMESPACE))
spec:
  roleName: ((CONFIG_NAME))-eks-cluster-role
  policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
---
apiVersion: identity.aws.crossplane.io/v1alpha2
kind: IAMRolePolicyAttachment
metadata:
  name: ((CONFIG_NAME))-role-clusterpolicy
  namespace: ((NAMESPACE))
spec:
  roleName: ((CONFIG_NAME))-eks-cluster-role
  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
