apiVersion: network.aws.crossplane.io/v1alpha2
kind: InternetGateway
metadata:
  name: ((CONFIG_NAME))-internetgateway
  namespace: ((NAMESPACE))
spec:
  vpcId: ((VPC_ID))
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
