apiVersion: network.aws.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  name: ((CONFIG_NAME))-rds-sg
  namespace: ((NAMESPACE))
spec:
  vpcId: ((VPC_ID))
  groupName: ((CONFIG_NAME))-rds-sg
  description: open rds access to crossplane workload
  reclaimPolicy: Delete
  ingress:
    - fromPort: 3306
      toPort: 3306
      protocol: tcp
      cidrBlocks:
        - cidrIp: 0.0.0.0/0
          description: all ips
  providerRef:
    name: aws-provider
    namespace: crossplane-system
