---
apiVersion: database.aws.crossplane.io/v1alpha2
kind: RDSInstanceClass
metadata:
  name: standard-mysql
  namespace: crossplane-system
specTemplate:
  class: db.t2.small
  masterUsername: masteruser
  securityGroups:
    - ((RDS_SECURITY_GROUP_ID))
  subnetGroupName: ((RDS_SUBNET_GROUP_NAME))
  size: 20
  engine: mysql
  providerRef:
    name: aws-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
---
apiVersion: compute.aws.crossplane.io/v1alpha2
kind: EKSClusterClass
metadata:
  name: standard-cluster
  namespace: crossplane-system
specTemplate:
  region: ((AWS_REGION))
  roleARN: ((EKS_ROLE_ARN))
  vpcId: ((VPC_ID))
  subnetIds:
    - ((SUBNET1_ID))
    - ((SUBNET2_ID))
    - ((SUBNET3_ID))
  securityGroupIds:
    - ((EKS_SECURITY_GROUP_ID))
  workerNodes:
    nodeInstanceType: m3.medium
    nodeAutoScalingGroupMinSize: 1
    nodeAutoScalingGroupMaxSize: 1
    nodeGroupName: demo-nodes
    clusterControlPlaneSecurityGroup: ((EKS_SECURITY_GROUP_ID))
  providerRef:
    name: aws-provider
    namespace: crossplane-system
  reclaimPolicy: Delete
