apiVersion: network.aws.crossplane.io/v1alpha2
kind: RouteTable
metadata:
  name: ((CONFIG_NAME))-routetable
  namespace: ((NAMESPACE))
spec:
  vpcId: ((VPC_ID))
  routes:
    - destinationCidrBlock: 0.0.0.0/0
      gatewayId: ((IG_ID))
  associations:
    - subnetId: ((SUBNET1_ID))
    - subnetId: ((SUBNET2_ID))
    - subnetId: ((SUBNET3_ID))
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
    namespace: crossplane-system
